# Generated by Django 5.2.11 on 2026-03-03 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=30)),
                ('provider', models.CharField(default='meta_cloud_api', max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('message_preview', models.TextField()),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shop.order')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
