# Generated by Django 5.2.11 on 2026-03-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_ordernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernotification',
            name='provider',
            field=models.CharField(default='email_smtp', max_length=50),
        ),
    ]
