# Generated by Django 5.2.11 on 2026-03-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_ordernotification_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernotification',
            name='recipient',
            field=models.CharField(max_length=254),
        ),
    ]
