# Generated by Django 5.2.11 on 2026-03-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_ordernotification_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_color',
            field=models.CharField(default='Noir', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_size',
            field=models.CharField(default='M', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='XS, S, M, L, XL, 2XL, 3XL, 4XL', help_text='List of sizes separated by comma', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(default='Noir, Vert', help_text='List of colors separated by comma', max_length=255),
        ),
    ]
