# Generated by Codex on 2026-03-03

from django.db import migrations


def populate_product_defaults(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')

    for product in Product.objects.select_related('category').all():
        category_slug = (product.category.slug or '').lower()
        product_name = (product.name or '').lower()

        if 'ceinture' in product_name or 'belt' in product_name:
            default_sizes = '10, 20, 30, 40, 50'
        elif category_slug in {'chemises', 'pantalons', 'costumes', 'nuit'}:
            default_sizes = 'XS, S, M, L, XL, 2XL, 3XL, 4XL'
        elif category_slug in {'montres', 'accessoires', 'maroquinerie'}:
            default_sizes = 'Unique'
        else:
            default_sizes = 'XS, S, M, L, XL, 2XL, 3XL, 4XL'

        product.colors = 'Noir, Vert'
        product.sizes = default_sizes
        product.save(update_fields=['colors', 'sizes'])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderitem_selected_color_orderitem_selected_size_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_product_defaults, migrations.RunPython.noop),
    ]
