# Generated by Django 5.2.12 on 2026-08-04 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_populate_product_colors_sizes_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='CamerPay', max_length=40)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('checkout_url', models.URLField(blank=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('currency', models.CharField(default='XAF', max_length=12)),
                ('payment_method', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('initiated', 'Initialisee'), ('pending', 'En attente'), ('success', 'Succes'), ('failed', 'Echec')], default='initiated', max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.order')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
